// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: flow_jobs.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const claimFlowJob = `-- name: ClaimFlowJob :one
UPDATE flow_jobs
SET status = 'running',
    attempts = attempts + 1,
    started_at = COALESCE(started_at, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'queued'
  AND (step <> 'retrying' OR updated_at <= CURRENT_TIMESTAMP - INTERVAL '3 seconds' * GREATEST(attempts, 1))
RETURNING id, flow_id, user_id, kind, status, step, attempts, max_attempts, error, correlation_id, payload, segments, created_at, started_at, finished_at, updated_at
`

func (q *Queries) ClaimFlowJob(ctx context.Context, id int64) (FlowJob, error) {
	row := q.db.QueryRowContext(ctx, claimFlowJob, id)
	var i FlowJob
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.Step,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CorrelationID,
		&i.Payload,
		&i.Segments,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeFlowJob = `-- name: CompleteFlowJob :one
UPDATE flow_jobs
SET status = 'succeeded',
    step = 'done',
    error = NULL,
    segments = $2,
    finished_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, flow_id, user_id, kind, status, step, attempts, max_attempts, error, correlation_id, payload, segments, created_at, started_at, finished_at, updated_at
`

type CompleteFlowJobParams struct {
	ID       int64           `json:"id"`
	Segments json.RawMessage `json:"segments"`
}

func (q *Queries) CompleteFlowJob(ctx context.Context, arg CompleteFlowJobParams) (FlowJob, error) {
	row := q.db.QueryRowContext(ctx, completeFlowJob, arg.ID, arg.Segments)
	var i FlowJob
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.Step,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CorrelationID,
		&i.Payload,
		&i.Segments,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlowJob = `-- name: CreateFlowJob :one
INSERT INTO flow_jobs (
  flow_id, user_id, kind, status, step, correlation_id, payload, max_attempts
)
VALUES (
  $1, $2, $3, 'queued', 'queued', $4, $5, $6
)
RETURNING id, flow_id, user_id, kind, status, step, attempts, max_attempts, error, correlation_id, payload, segments, created_at, started_at, finished_at, updated_at
`

type CreateFlowJobParams struct {
	FlowID        int64           `json:"flow_id"`
	UserID        int64           `json:"user_id"`
	Kind          string          `json:"kind"`
	CorrelationID string          `json:"correlation_id"`
	Payload       json.RawMessage `json:"payload"`
	MaxAttempts   int16           `json:"max_attempts"`
}

func (q *Queries) CreateFlowJob(ctx context.Context, arg CreateFlowJobParams) (FlowJob, error) {
	row := q.db.QueryRowContext(ctx, createFlowJob,
		arg.FlowID,
		arg.UserID,
		arg.Kind,
		arg.CorrelationID,
		arg.Payload,
		arg.MaxAttempts,
	)
	var i FlowJob
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.Step,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CorrelationID,
		&i.Payload,
		&i.Segments,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlowWithJob = `-- name: CreateFlowWithJob :one
WITH new_flow AS (
  INSERT INTO flows (title, status, model, model_provider_name, model_provider_type,
                     language, tool_call_id_template, functions, user_id)
  VALUES ('untitled', 'created', 'unknown', $1, $2, 'English', $3, '{}', $4)
  RETURNING id, status, title, model, model_provider_name, language, functions, user_id, created_at, updated_at, deleted_at, trace_id, model_provider_type, tool_call_id_template
), new_job AS (
  INSERT INTO flow_jobs (flow_id, user_id, kind, correlation_id, payload, max_attempts)
  SELECT id, user_id, 'create', $5, $6, $7 FROM new_flow
  RETURNING flow_id
)
SELECT new_flow.id, new_flow.status, new_flow.title, new_flow.model, new_flow.model_provider_name, new_flow.language, new_flow.functions, new_flow.user_id, new_flow.created_at, new_flow.updated_at, new_flow.deleted_at, new_flow.trace_id, new_flow.model_provider_type, new_flow.tool_call_id_template FROM new_flow JOIN new_job ON new_job.flow_id = new_flow.id
`

type CreateFlowWithJobParams struct {
	ModelProviderName  string          `json:"model_provider_name"`
	ModelProviderType  ProviderType    `json:"model_provider_type"`
	ToolCallIDTemplate string          `json:"tool_call_id_template"`
	UserID             int64           `json:"user_id"`
	CorrelationID      string          `json:"correlation_id"`
	Payload            json.RawMessage `json:"payload"`
	MaxAttempts        int16           `json:"max_attempts"`
}

type CreateFlowWithJobRow struct {
	ID                 int64           `json:"id"`
	Status             FlowStatus      `json:"status"`
	Title              string          `json:"title"`
	Model              string          `json:"model"`
	ModelProviderName  string          `json:"model_provider_name"`
	Language           string          `json:"language"`
	Functions          json.RawMessage `json:"functions"`
	UserID             int64           `json:"user_id"`
	CreatedAt          sql.NullTime    `json:"created_at"`
	UpdatedAt          sql.NullTime    `json:"updated_at"`
	DeletedAt          sql.NullTime    `json:"deleted_at"`
	TraceID            sql.NullString  `json:"trace_id"`
	ModelProviderType  ProviderType    `json:"model_provider_type"`
	ToolCallIDTemplate string          `json:"tool_call_id_template"`
}

// Both records commit together; a failed job insert cannot leave an orphan flow.
func (q *Queries) CreateFlowWithJob(ctx context.Context, arg CreateFlowWithJobParams) (CreateFlowWithJobRow, error) {
	row := q.db.QueryRowContext(ctx, createFlowWithJob,
		arg.ModelProviderName,
		arg.ModelProviderType,
		arg.ToolCallIDTemplate,
		arg.UserID,
		arg.CorrelationID,
		arg.Payload,
		arg.MaxAttempts,
	)
	var i CreateFlowWithJobRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Model,
		&i.ModelProviderName,
		&i.Language,
		&i.Functions,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TraceID,
		&i.ModelProviderType,
		&i.ToolCallIDTemplate,
	)
	return i, err
}

const deleteFinishedFlowJobsOlderThan = `-- name: DeleteFinishedFlowJobsOlderThan :exec
DELETE FROM flow_jobs
WHERE status IN ('succeeded', 'failed') AND updated_at < $1
`

func (q *Queries) DeleteFinishedFlowJobsOlderThan(ctx context.Context, updatedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteFinishedFlowJobsOlderThan, updatedAt)
	return err
}

const failFlowJob = `-- name: FailFlowJob :one
UPDATE flow_jobs
SET status = 'failed',
    step = 'failed',
    error = $2,
    segments = $3,
    finished_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, flow_id, user_id, kind, status, step, attempts, max_attempts, error, correlation_id, payload, segments, created_at, started_at, finished_at, updated_at
`

type FailFlowJobParams struct {
	ID       int64           `json:"id"`
	Error    sql.NullString  `json:"error"`
	Segments json.RawMessage `json:"segments"`
}

func (q *Queries) FailFlowJob(ctx context.Context, arg FailFlowJobParams) (FlowJob, error) {
	row := q.db.QueryRowContext(ctx, failFlowJob, arg.ID, arg.Error, arg.Segments)
	var i FlowJob
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.Step,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CorrelationID,
		&i.Payload,
		&i.Segments,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveFlowJob = `-- name: GetActiveFlowJob :one
SELECT
  id, flow_id, user_id, kind, status, step, attempts, max_attempts, error, correlation_id, payload, segments, created_at, started_at, finished_at, updated_at
FROM flow_jobs
WHERE flow_id = $1 AND kind = $2 AND status IN ('queued', 'running')
ORDER BY id DESC
LIMIT 1
`

type GetActiveFlowJobParams struct {
	FlowID int64  `json:"flow_id"`
	Kind   string `json:"kind"`
}

func (q *Queries) GetActiveFlowJob(ctx context.Context, arg GetActiveFlowJobParams) (FlowJob, error) {
	row := q.db.QueryRowContext(ctx, getActiveFlowJob, arg.FlowID, arg.Kind)
	var i FlowJob
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.Step,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CorrelationID,
		&i.Payload,
		&i.Segments,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlowJob = `-- name: GetFlowJob :one
SELECT
  id, flow_id, user_id, kind, status, step, attempts, max_attempts, error, correlation_id, payload, segments, created_at, started_at, finished_at, updated_at
FROM flow_jobs
WHERE id = $1
`

func (q *Queries) GetFlowJob(ctx context.Context, id int64) (FlowJob, error) {
	row := q.db.QueryRowContext(ctx, getFlowJob, id)
	var i FlowJob
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.Step,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CorrelationID,
		&i.Payload,
		&i.Segments,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestFlowJob = `-- name: GetLatestFlowJob :one
SELECT
  id, flow_id, user_id, kind, status, step, attempts, max_attempts, error, correlation_id, payload, segments, created_at, started_at, finished_at, updated_at
FROM flow_jobs
WHERE flow_id = $1
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestFlowJob(ctx context.Context, flowID int64) (FlowJob, error) {
	row := q.db.QueryRowContext(ctx, getLatestFlowJob, flowID)
	var i FlowJob
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.Step,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CorrelationID,
		&i.Payload,
		&i.Segments,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestFlowJobsByFlowIDs = `-- name: GetLatestFlowJobsByFlowIDs :many
SELECT DISTINCT ON (flow_id)
  id, flow_id, user_id, kind, status, step, attempts, max_attempts, error, correlation_id, payload, segments, created_at, started_at, finished_at, updated_at
FROM flow_jobs
WHERE flow_id = ANY($1::bigint[])
ORDER BY flow_id, id DESC
`

func (q *Queries) GetLatestFlowJobsByFlowIDs(ctx context.Context, dollar_1 []int64) ([]FlowJob, error) {
	rows, err := q.db.QueryContext(ctx, getLatestFlowJobsByFlowIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowJob
	for rows.Next() {
		var i FlowJob
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.UserID,
			&i.Kind,
			&i.Status,
			&i.Step,
			&i.Attempts,
			&i.MaxAttempts,
			&i.Error,
			&i.CorrelationID,
			&i.Payload,
			&i.Segments,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingFlowJobs = `-- name: ListPendingFlowJobs :many
SELECT
  id, flow_id, user_id, kind, status, step, attempts, max_attempts, error, correlation_id, payload, segments, created_at, started_at, finished_at, updated_at
FROM flow_jobs
WHERE status IN ('queued', 'running')
  AND (kind <> 'stop' OR step = 'recovered')
  AND (step <> 'retrying' OR updated_at <= CURRENT_TIMESTAMP - INTERVAL '3 seconds' * GREATEST(attempts, 1))
ORDER BY id
LIMIT $1::bigint
`

func (q *Queries) ListPendingFlowJobs(ctx context.Context, dollar_1 int64) ([]FlowJob, error) {
	rows, err := q.db.QueryContext(ctx, listPendingFlowJobs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowJob
	for rows.Next() {
		var i FlowJob
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.UserID,
			&i.Kind,
			&i.Status,
			&i.Step,
			&i.Attempts,
			&i.MaxAttempts,
			&i.Error,
			&i.CorrelationID,
			&i.Payload,
			&i.Segments,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverInterruptedFlowJobs = `-- name: RecoverInterruptedFlowJobs :many
UPDATE flow_jobs
SET status = 'queued',
    step = 'recovered',
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'running'
RETURNING id, flow_id, user_id, kind, status, step, attempts, max_attempts, error, correlation_id, payload, segments, created_at, started_at, finished_at, updated_at
`

// A job left running belongs to a process that died. It goes back to the queue
// (keeping its attempts count) so start-up can retry or fail it explicitly
// rather than leaving it "running" forever.
func (q *Queries) RecoverInterruptedFlowJobs(ctx context.Context) ([]FlowJob, error) {
	rows, err := q.db.QueryContext(ctx, recoverInterruptedFlowJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowJob
	for rows.Next() {
		var i FlowJob
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.UserID,
			&i.Kind,
			&i.Status,
			&i.Step,
			&i.Attempts,
			&i.MaxAttempts,
			&i.Error,
			&i.CorrelationID,
			&i.Payload,
			&i.Segments,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueFlowJob = `-- name: RequeueFlowJob :one
UPDATE flow_jobs
SET status = 'queued',
    step = $2,
    error = $3,
    segments = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, flow_id, user_id, kind, status, step, attempts, max_attempts, error, correlation_id, payload, segments, created_at, started_at, finished_at, updated_at
`

type RequeueFlowJobParams struct {
	ID       int64           `json:"id"`
	Step     string          `json:"step"`
	Error    sql.NullString  `json:"error"`
	Segments json.RawMessage `json:"segments"`
}

func (q *Queries) RequeueFlowJob(ctx context.Context, arg RequeueFlowJobParams) (FlowJob, error) {
	row := q.db.QueryRowContext(ctx, requeueFlowJob,
		arg.ID,
		arg.Step,
		arg.Error,
		arg.Segments,
	)
	var i FlowJob
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.Step,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CorrelationID,
		&i.Payload,
		&i.Segments,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlowJobProgress = `-- name: UpdateFlowJobProgress :one
UPDATE flow_jobs
SET step = $2,
    segments = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, flow_id, user_id, kind, status, step, attempts, max_attempts, error, correlation_id, payload, segments, created_at, started_at, finished_at, updated_at
`

type UpdateFlowJobProgressParams struct {
	ID       int64           `json:"id"`
	Step     string          `json:"step"`
	Segments json.RawMessage `json:"segments"`
}

func (q *Queries) UpdateFlowJobProgress(ctx context.Context, arg UpdateFlowJobProgressParams) (FlowJob, error) {
	row := q.db.QueryRowContext(ctx, updateFlowJobProgress, arg.ID, arg.Step, arg.Segments)
	var i FlowJob
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.Step,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CorrelationID,
		&i.Payload,
		&i.Segments,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}
